filters:
   - include-code-files
   
project:
  type: book
  execute-dir: "project"
  output-dir: ./_site
  preview:
    port: 4200
    browser: true

book:
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: course-content/cover.png
  output-file: "course-ml"
  title: "Introduction to Machine Learning (Makine Öğrenmesine giriş)"
  chapters:
      - index.qmd
      - course-content/syllabus.qmd

bibliography: references.bib 

profile:
  default: tr
  group: 
    - [def,en,tr]



format:
  html:
    smooth-scroll: true
    link-external-icon: true
    toc-location: left
    toc-expand: false
    theme: cosmo
    mermaid:
      theme: forest
  pdf:
    documentclass: scrreprt
    keep-tex: true
    toc: true
    number-sections: true
    paper-size: 
    cite-method: natbib     
    colorlinks: true    
    latex-output-dir: .
    output-file: main
    mermaid:
      theme: forest
